### ISSUE TITLE
Fully documented API is missing

### ISSUE THREAD

**Issue by marcelvoss** [marcelvoss/MVDribbbleKit#4]
It would be nice to have a fully documented API (every property, every method, every typedef). I would really appreciate the help of others with this task because it is a time consuming work but would make the API infinitely easier to use.

Thanks in advance to everyone!

**Comment by marcelvoss** [comment]
Thanks to @dkhamsing! You're pretty awesome!

**Comment by dkhamsing** [comment]
Thanks for your work
